version: '3'

services:
  app:
    ports:
      - "${PORT}:${PORT}"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: "${PORT}"
        LOG_ENV": "${LOG}"
        BIT_USER: "${BIT_USER}"
        BIT_APP_PASS: "${BIT_APP_PASS}"
        GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
        GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT}"
        GOOGLE_CLOUD_DATASET: "${GOOGLE_CLOUD_DATASET}"
    volumes:
      - "./src:/app:rw"
      - ~/.config/gcloud:/app/credentials